Repository iPlayed-games/frontend, pull requests merged in 2023-08, with the labels that each got.

#42 22 esling prettier config
  .eslintrc.json
  .github/workflows/docker.yaml
  .prettierrc.json
  jest.config.js
  package-lock.json
  package.json
  src/__tests__/index.test.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/utils/add.ts
Labels: PR

#56 48 update install readme
  README.md
Labels: documentation

#57 32-run lint and test
  .github/workflows/cicd.yaml
  .github/workflows/docker.yaml
  .gitignore
  README.md
  package-lock.json
  package.json
Labels: update

#58 49-Adding how to use .env instructions
  .env-template
  .gitignore
  README.md
Labels: PR

#62 37 create header
  .github/workflows/cicd.yaml
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/.keep
  src/components/Header/Header.tsx
  src/components/Header/style.tsx
  src/components/Logo/Logo.module.css
  src/components/Logo/Logo.tsx
  src/components/Searchbar/Searchbar.module.css
  src/components/Searchbar/Searchbar.tsx
  src/styles/.keep
  src/styles/styles.ts
  src/tempData.ts
Labels: help wanted, PR

#70 36 mock data
  src/components/Searchbar/Searchbar.tsx
  src/data/activitiesMockData.ts
  src/data/locationsMockData.ts
  src/data/tempData.ts
  src/data/usersMockData.ts
  src/data/venuesMockData.ts
  src/types/.keep
  src/types/activityType.ts
  src/types/locationType.ts
  src/types/userType.ts
  src/types/venueType.ts
Labels: PR

#75 73 install husky for lint before commit
  .gitignore
  .husky/pre-commit
  package-lock.json
  package.json
  src/app/layout.tsx
Labels: PR

#74 71-Footer-padding-and-fontColor
  src/app/_document.tsx
  src/app/global.css
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
  src/components/Footer/styles.ts
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/components/Hero/index.tsx
  src/components/Logo/Logo.module.css
  src/components/Logo/Logo.tsx
  src/components/index.tsx
  src/data/activitiesMockData.ts
  src/data/locationsMockData.ts
  src/data/usersMockData.ts
  src/data/venuesMockData.ts
  src/styles/.keep
  src/styles/_variables.js
  src/types/activity.ts
  src/types/location.ts
  src/types/user.ts
  src/types/venue.ts
  src/utils/.keep
Labels: PR

#76 68 paths tsconfig created
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Footer/index.tsx
  src/components/Footer/styles.ts
  src/data/activitiesMockData.ts
  src/data/locationsMockData.ts
  src/data/usersMockData.ts
  src/data/venuesMockData.ts
  src/typing/activityType.ts
  src/typing/locationType.ts
  src/typing/userType.ts
  src/typing/venueType.ts
  tsconfig.json
Labels: PR

#81 80-create section title component with gradient background
  src/common/SectionTitle/index.tsx
  src/common/SectionTitle/style.ts
  src/common/index.tsx
  src/styles/_variables.js
Labels: PR
